services:
  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    volumes:
      - \\wsl.localhost\Ubuntu\home\jesse\open-webui:/app/backend/data
    ports:
      -  ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'WEBUI_NAME=${WEBUI_NAME}'
      - 'VECTOR_DB=${VECTOR_DB}'
      - 'QDRANT_URI=${QDRANT_URI}'
      - 'QDRANT_API_KEY=${QDRANT_API_KEY}'
      - 'AIOHTTP_CLIENT_TIMEOUT=${AIOHTTP_CLIENT_TIMEOUT-6000}'
      - 'DATABASE_URL=${DATABASE_URL}'
      - 'ENABLE_WEBSOCKET_SUPPORT=${ENABLE_WEBSOCKET_SUPPORT-true}'
      - 'WEBSOCKET_MANAGER=${WEBSOCKET_MANAGER-redis}'
      - 'WEBSOCKET_REDIS_URL=${WEBSOCKET_REDIS_URL}'
      - 'WEBSOCKET_REDIS_LOCK_TIMEOUT=${WEBSOCKET_REDIS_LOCK_TIMEOUT-300}'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - open-webui-shared
    restart: unless-stopped
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    volumes:
      - pipelines-data:/app/pipelines
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - open-webui-shared
    restart: unless-stopped
  kokoro-tts:
    image: ghcr.io/remsky/kokoro-fastapi-gpu:latest
    ports:
      - "8880:8880"
    volumes:
      - kokoro-data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - open-webui-shared
    restart: unless-stopped
  whisper-stt-adapter:
    build:
      context: ./whisper-webui-adapter
      dockerfile: Dockerfile
    environment:
      - 'WHISPER_WEBUI_BASE_URL=https://whisper-webui.myia.io'
      - 'WHISPER_WEBUI_USERNAME=admin'
      - 'WHISPER_WEBUI_PASSWORD=goldman'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - open-webui-shared
    restart: unless-stopped

volumes:
  open-webui: {}
  pipelines-data: {}
  kokoro-data: {}

networks:
  open-webui-shared:
    external: true
